#!/usr/bin/env bun

import solidPlugin from '@opentui/solid/scripts/solid-plugin.ts'
import path from "path"
import fs from "fs"
import { $ } from "bun"
import { fileURLToPath } from "url"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const dir = path.resolve(__dirname, "..")

process.chdir(dir)

import pkg from "../package.json"
import { Script } from "@cyberstrike-io/script"
const modelsUrl = process.env.CYBERSTRIKE_MODELS_URL || "https://models.dev"
// Fetch and generate models.dev snapshot
const modelsData = process.env.MODELS_DEV_API_JSON
  ? await Bun.file(process.env.MODELS_DEV_API_JSON).text()
  : await fetch(`${modelsUrl}/api.json`).then((x) => x.text())
await Bun.write(
  path.join(dir, "src/provider/models-snapshot.ts"),
  `// Auto-generated by build.ts - do not edit\nexport const snapshot = ${modelsData} as const\n`,
)
console.log("Generated models-snapshot.ts")

// Load migrations from migration directories
const migrationDirs = (await fs.promises.readdir(path.join(dir, "migration"), { withFileTypes: true }))
  .filter((entry) => entry.isDirectory() && /^\d{4}\d{2}\d{2}\d{2}\d{2}\d{2}/.test(entry.name))
  .map((entry) => entry.name)
  .sort()

const migrations = await Promise.all(
  migrationDirs.map(async (name) => {
    const file = path.join(dir, "migration", name, "migration.sql")
    const sql = await Bun.file(file).text()
    const match = /^(\d{4})(\d{2})(\d{2})(\d{2})(\d{2})(\d{2})/.exec(name)
    const timestamp = match
      ? Date.UTC(
        Number(match[1]),
        Number(match[2]) - 1,
        Number(match[3]),
        Number(match[4]),
        Number(match[5]),
        Number(match[6]),
      )
      : 0
    return { sql, timestamp }
  }),
)
console.log(`Loaded ${migrations.length} migrations`)

const singleFlag = process.argv.includes("--single")
const baselineFlag = process.argv.includes("--baseline")
const skipInstall = process.argv.includes("--skip-install")

const allTargets: {
  os: string
  arch: "arm64" | "x64"
  abi?: "musl"
  avx2?: false
}[] = [
    {
      os: "linux",
      arch: "arm64",
    },
    {
      os: "linux",
      arch: "x64",
    },
    {
      os: "linux",
      arch: "x64",
      avx2: false,
    },
    {
      os: "linux",
      arch: "arm64",
      abi: "musl",
    },
    {
      os: "linux",
      arch: "x64",
      abi: "musl",
    },
    {
      os: "linux",
      arch: "x64",
      abi: "musl",
      avx2: false,
    },
    {
      os: "darwin",
      arch: "arm64",
    },
    {
      os: "darwin",
      arch: "x64",
    },
    {
      os: "darwin",
      arch: "x64",
      avx2: false,
    },
    {
      os: "win32",
      arch: "x64",
    },
    {
      os: "win32",
      arch: "x64",
      avx2: false,
    },
  ]

const targets = singleFlag
  ? allTargets.filter((item) => {
    if (item.os !== process.platform || item.arch !== process.arch) {
      return false
    }

    // When building for the current platform, prefer a single native binary by default.
    // Baseline binaries require additional Bun artifacts and can be flaky to download.
    if (item.avx2 === false) {
      return baselineFlag
    }

    // also skip abi-specific builds for the same reason
    if (item.abi !== undefined) {
      return false
    }

    return true
  })
  : allTargets

await $`rm -rf dist`

const binaries: Record<string, string> = {}
if (!skipInstall) {
  await $`bun install --os="*" --cpu="*" @opentui/core@${pkg.dependencies["@opentui/core"]}`
  await $`bun install --os="*" --cpu="*" @parcel/watcher@${pkg.dependencies["@parcel/watcher"]}`
}
for (const item of targets) {
  const name = [
    pkg.name,
    // changing to win32 flags npm for some reason
    item.os === "win32" ? "windows" : item.os,
    item.arch,
    item.avx2 === false ? "baseline" : undefined,
    item.abi === undefined ? undefined : item.abi,
  ]
    .filter(Boolean)
    .join("-")
  console.log(`building ${name}`)
  await $`mkdir -p dist/${name}/bin`

  const parserWorker = fs.realpathSync(path.resolve(dir, "./node_modules/@opentui/core/parser.worker.js"))
  const workerPath = "./src/cli/cmd/tui/worker.ts"

  // Use platform-specific bunfs root path based on target OS
  const bunfsRoot = item.os === "win32" ? "B:/~BUN/root/" : "/$bunfs/root/"
  const workerRelativePath = path.relative(dir, parserWorker).replaceAll("\\", "/")

  await Bun.build({
    conditions: ["browser"],
    tsconfig: "./tsconfig.json",
    plugins: [solidPlugin],
    sourcemap: "external",
    // Main binary has ZERO playwright references (subprocess.md): hackbrowser
    // runs in a separate worker process (hackbrowser-worker.js). No playwright
    // external list needed here — if playwright somehow slips in, the build
    // will fail loudly at compile time rather than silently at user startup.
    // chromium-bidi / electron: optional Playwright backends not used by CDP
    // path. Kept to prevent "Could not resolve" errors if any transitive dep
    // still references them (INTEGRATION.md §10.1).
    external: ["chromium-bidi", "electron"],
    compile: {
      autoloadBunfig: false,
      autoloadDotenv: false,
      //@ts-ignore (bun types aren't up to date)
      autoloadTsconfig: true,
      autoloadPackageJson: true,
      target: name.replace(pkg.name, "bun") as any,
      outfile: `dist/${name}/bin/cyberstrike`,
      execArgv: [`--user-agent=cyberstrike/${Script.version}`, "--use-system-ca", "--"],
      windows: {},
    },
    entrypoints: ["./src/index.ts", parserWorker, workerPath],
    define: {
      CYBERSTRIKE_VERSION: `'${Script.version}'`,
      CYBERSTRIKE_MIGRATIONS: JSON.stringify(migrations),
      OTUI_TREE_SITTER_WORKER_PATH: bunfsRoot + workerRelativePath,
      CYBERSTRIKE_WORKER_PATH: workerPath,
      CYBERSTRIKE_CHANNEL: `'${Script.channel}'`,
      CYBERSTRIKE_LIBC: item.os === "linux" ? `'${item.abi ?? "glibc"}'` : "",
    },
  })

  await $`rm -rf ./dist/${name}/bin/tui`
  await Bun.file(`dist/${name}/package.json`).write(
    JSON.stringify(
      {
        name: `@cyberstrike-io/${name}`,
        version: Script.version,
        os: [item.os],
        cpu: [item.arch],
      },
      null,
      2,
    ),
  )
  binaries[name] = Script.version
}

// ============================================================
// Worker JS build — hackbrowser subprocess (subprocess.md)
// ============================================================
//
// Built as a plain JS bundle (NOT a Bun compile) so it can be run with
// bun or node and resolve playwright at runtime from node_modules next
// to the worker file. playwright/playwright-core are external so they
// are not baked in here either — they live in
// ~/.local/share/cyberstrike/node_modules/ and are installed by postinstall.
// chromium-bidi / electron: excluded for the same reason as in the main build.

await $`mkdir -p dist/hackbrowser-worker`
const workerBuildResult = await Bun.build({
  entrypoints: ["./src/hackbrowser-subprocess/hackbrowser-worker.ts"],
  outdir: "./dist/hackbrowser-worker",
  target: "node",
  external: ["playwright", "playwright-core", "chromium-bidi", "electron"],
  minify: false,
  sourcemap: "none",
})
if (!workerBuildResult.success) {
  console.error("hackbrowser-worker build failed:")
  for (const log of workerBuildResult.logs) console.error(log)
  process.exit(1)
}
console.log("hackbrowser-worker.js built")

// Copy worker into each platform's bin/ so it's included in release archives.
// install.sh users get the worker alongside the binary without needing npm.
for (const key of Object.keys(binaries)) {
  await $`cp dist/hackbrowser-worker/hackbrowser-worker.js dist/${key}/bin/hackbrowser-worker.js`
}
console.log("hackbrowser-worker.js copied to all platform bin/ directories")

if (Script.release) {
  for (const key of Object.keys(binaries)) {
    if (key.includes("linux")) {
      await $`tar -czf ../../${key}.tar.gz *`.cwd(`dist/${key}/bin`)
    } else {
      await $`zip -r ../../${key}.zip *`.cwd(`dist/${key}/bin`)
    }
  }
  await $`gh release upload v${Script.version} ./dist/*.zip ./dist/*.tar.gz --clobber`
}

export { binaries }
